// Generated by rstantools.  Do not edit by hand.

/*
    pisquared is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    pisquared is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with pisquared.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.19.1

#include <stan/model/model_header.hpp>

namespace model_pi0_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_pi0");
    reader.add_event(27, 25, "end", "model_pi0");
    return reader;
}

#include <stan_meta_header.hpp>
 class model_pi0 : public prob_grad {
private:
        int N;
        vector_d pvalues;
        vector_d weights;
        int beta_fixed;
        std::vector<double> alpha_prior;
        std::vector<double> beta_prior;
public:
    model_pi0(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }

    model_pi0(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;

        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "model_pi0_namespace::model_pi0";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {
            // initialize data block variables from context__
            current_statement_begin__ = 2;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            check_greater_or_equal(function__, "N", N, 0);

            current_statement_begin__ = 3;
            validate_non_negative_index("pvalues", "N", N);
            context__.validate_dims("data initialization", "pvalues", "vector_d", context__.to_vec(N));
            pvalues = Eigen::Matrix<double, Eigen::Dynamic, 1>(N);
            vals_r__ = context__.vals_r("pvalues");
            pos__ = 0;
            size_t pvalues_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < pvalues_j_1_max__; ++j_1__) {
                pvalues(j_1__) = vals_r__[pos__++];
            }

            current_statement_begin__ = 4;
            validate_non_negative_index("weights", "N", N);
            context__.validate_dims("data initialization", "weights", "vector_d", context__.to_vec(N));
            weights = Eigen::Matrix<double, Eigen::Dynamic, 1>(N);
            vals_r__ = context__.vals_r("weights");
            pos__ = 0;
            size_t weights_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < weights_j_1_max__; ++j_1__) {
                weights(j_1__) = vals_r__[pos__++];
            }

            current_statement_begin__ = 5;
            context__.validate_dims("data initialization", "beta_fixed", "int", context__.to_vec());
            beta_fixed = int(0);
            vals_i__ = context__.vals_i("beta_fixed");
            pos__ = 0;
            beta_fixed = vals_i__[pos__++];
            check_greater_or_equal(function__, "beta_fixed", beta_fixed, 0);
            check_less_or_equal(function__, "beta_fixed", beta_fixed, 1);

            current_statement_begin__ = 6;
            validate_non_negative_index("alpha_prior", "2", 2);
            context__.validate_dims("data initialization", "alpha_prior", "double", context__.to_vec(2));
            alpha_prior = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("alpha_prior");
            pos__ = 0;
            size_t alpha_prior_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < alpha_prior_k_0_max__; ++k_0__) {
                alpha_prior[k_0__] = vals_r__[pos__++];
            }

            current_statement_begin__ = 7;
            validate_non_negative_index("beta_prior", "2", 2);
            context__.validate_dims("data initialization", "beta_prior", "double", context__.to_vec(2));
            beta_prior = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("beta_prior");
            pos__ = 0;
            size_t beta_prior_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < beta_prior_k_0_max__; ++k_0__) {
                beta_prior[k_0__] = vals_r__[pos__++];
            }


            // initialize transformed data variables
            // execute transformed data statements

            // validate transformed data

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 10;
            num_params_r__ += 1;
            current_statement_begin__ = 11;
            num_params_r__ += 1;
            current_statement_begin__ = 12;
            validate_non_negative_index("beta_minus_one", "(beta_fixed ? 0 : 1 )", (beta_fixed ? 0 : 1 ));
            num_params_r__ += (1 * (beta_fixed ? 0 : 1 ));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~model_pi0() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        current_statement_begin__ = 10;
        if (!(context__.contains_r("pi0")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable pi0 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("pi0");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "pi0", "double", context__.to_vec());
        double pi0(0);
        pi0 = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(0, 1, pi0);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable pi0: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 11;
        if (!(context__.contains_r("alpha")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable alpha missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("alpha");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "alpha", "double", context__.to_vec());
        double alpha(0);
        alpha = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(0, 1, alpha);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable alpha: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 12;
        if (!(context__.contains_r("beta_minus_one")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta_minus_one missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta_minus_one");
        pos__ = 0U;
        validate_non_negative_index("beta_minus_one", "(beta_fixed ? 0 : 1 )", (beta_fixed ? 0 : 1 ));
        context__.validate_dims("parameter initialization", "beta_minus_one", "double", context__.to_vec((beta_fixed ? 0 : 1 )));
        std::vector<double> beta_minus_one((beta_fixed ? 0 : 1 ), double(0));
        size_t beta_minus_one_k_0_max__ = (beta_fixed ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < beta_minus_one_k_0_max__; ++k_0__) {
            beta_minus_one[k_0__] = vals_r__[pos__++];
        }
        size_t beta_minus_one_i_0_max__ = (beta_fixed ? 0 : 1 );
        for (size_t i_0__ = 0; i_0__ < beta_minus_one_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, beta_minus_one[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta_minus_one: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        typedef T__ local_scalar_t__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);

            // model parameters
            current_statement_begin__ = 10;
            local_scalar_t__ pi0;
            (void) pi0;  // dummy to suppress unused var warning
            if (jacobian__)
                pi0 = in__.scalar_lub_constrain(0, 1, lp__);
            else
                pi0 = in__.scalar_lub_constrain(0, 1);

            current_statement_begin__ = 11;
            local_scalar_t__ alpha;
            (void) alpha;  // dummy to suppress unused var warning
            if (jacobian__)
                alpha = in__.scalar_lub_constrain(0, 1, lp__);
            else
                alpha = in__.scalar_lub_constrain(0, 1);

            current_statement_begin__ = 12;
            std::vector<local_scalar_t__> beta_minus_one;
            size_t beta_minus_one_d_0_max__ = (beta_fixed ? 0 : 1 );
            beta_minus_one.reserve(beta_minus_one_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < beta_minus_one_d_0_max__; ++d_0__) {
                if (jacobian__)
                    beta_minus_one.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    beta_minus_one.push_back(in__.scalar_lb_constrain(0));
            }

            // transformed parameters
            current_statement_begin__ = 15;
            local_scalar_t__ beta;
            (void) beta;  // dummy to suppress unused var warning
            stan::math::initialize(beta, DUMMY_VAR__);
            stan::math::fill(beta, DUMMY_VAR__);
            stan::math::assign(beta,(beta_fixed ? stan::math::promote_scalar<local_scalar_t__>(1.0) : stan::math::promote_scalar<local_scalar_t__>((get_base1(beta_minus_one, 1, "beta_minus_one", 1) + 1.0)) ));

            current_statement_begin__ = 16;
            local_scalar_t__ log_pi0;
            (void) log_pi0;  // dummy to suppress unused var warning
            stan::math::initialize(log_pi0, DUMMY_VAR__);
            stan::math::fill(log_pi0, DUMMY_VAR__);
            stan::math::assign(log_pi0,stan::math::log(pi0));

            current_statement_begin__ = 17;
            local_scalar_t__ log1m_pi0;
            (void) log1m_pi0;  // dummy to suppress unused var warning
            stan::math::initialize(log1m_pi0, DUMMY_VAR__);
            stan::math::fill(log1m_pi0, DUMMY_VAR__);
            stan::math::assign(log1m_pi0,log1m(pi0));

            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning

            current_statement_begin__ = 15;
            if (stan::math::is_uninitialized(beta)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: beta";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable beta: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            current_statement_begin__ = 16;
            if (stan::math::is_uninitialized(log_pi0)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: log_pi0";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable log_pi0: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            current_statement_begin__ = 17;
            if (stan::math::is_uninitialized(log1m_pi0)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: log1m_pi0";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable log1m_pi0: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }

            // model body

            current_statement_begin__ = 20;
            lp_accum__.add(beta_log<propto__>(alpha, get_base1(alpha_prior, 1, "alpha_prior", 1), get_base1(alpha_prior, 2, "alpha_prior", 1)));
            current_statement_begin__ = 21;
            if (as_bool(logical_gt(get_base1(beta_prior, 2, "beta_prior", 1), 0))) {
                current_statement_begin__ = 21;
                lp_accum__.add(gamma_log<propto__>(beta_minus_one, get_base1(beta_prior, 1, "beta_prior", 1), get_base1(beta_prior, 2, "beta_prior", 1)));
            }
            current_statement_begin__ = 22;
            for (int i = 1; i <= N; ++i) {

                current_statement_begin__ = 23;
                lp_accum__.add((get_base1(weights, i, "weights", 1) * log_sum_exp(log_pi0, (log1m_pi0 + beta_log(get_base1(pvalues, i, "pvalues", 1), alpha, beta)))));
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("pi0");
        names__.push_back("alpha");
        names__.push_back("beta_minus_one");
        names__.push_back("beta");
        names__.push_back("log_pi0");
        names__.push_back("log1m_pi0");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((beta_fixed ? 0 : 1 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;

        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_pi0_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning

        // read-transform, write parameters
        double pi0 = in__.scalar_lub_constrain(0, 1);
        vars__.push_back(pi0);

        double alpha = in__.scalar_lub_constrain(0, 1);
        vars__.push_back(alpha);

        std::vector<double> beta_minus_one;
        size_t beta_minus_one_d_0_max__ = (beta_fixed ? 0 : 1 );
        beta_minus_one.reserve(beta_minus_one_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < beta_minus_one_d_0_max__; ++d_0__) {
            beta_minus_one.push_back(in__.scalar_lb_constrain(0));
        }
        size_t beta_minus_one_k_0_max__ = (beta_fixed ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < beta_minus_one_k_0_max__; ++k_0__) {
            vars__.push_back(beta_minus_one[k_0__]);
        }

        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        if (!include_tparams__ && !include_gqs__) return;

        try {
            // declare and define transformed parameters
            current_statement_begin__ = 15;
            double beta;
            (void) beta;  // dummy to suppress unused var warning
            stan::math::initialize(beta, DUMMY_VAR__);
            stan::math::fill(beta, DUMMY_VAR__);
            stan::math::assign(beta,(beta_fixed ? stan::math::promote_scalar<local_scalar_t__>(1.0) : stan::math::promote_scalar<local_scalar_t__>((get_base1(beta_minus_one, 1, "beta_minus_one", 1) + 1.0)) ));

            current_statement_begin__ = 16;
            double log_pi0;
            (void) log_pi0;  // dummy to suppress unused var warning
            stan::math::initialize(log_pi0, DUMMY_VAR__);
            stan::math::fill(log_pi0, DUMMY_VAR__);
            stan::math::assign(log_pi0,stan::math::log(pi0));

            current_statement_begin__ = 17;
            double log1m_pi0;
            (void) log1m_pi0;  // dummy to suppress unused var warning
            stan::math::initialize(log1m_pi0, DUMMY_VAR__);
            stan::math::fill(log1m_pi0, DUMMY_VAR__);
            stan::math::assign(log1m_pi0,log1m(pi0));

            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning

            // write transformed parameters
            if (include_tparams__) {
                vars__.push_back(beta);
                vars__.push_back(log_pi0);
                vars__.push_back(log1m_pi0);
            }
            if (!include_gqs__) return;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "model_pi0";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "pi0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha";
        param_names__.push_back(param_name_stream__.str());
        size_t beta_minus_one_k_0_max__ = (beta_fixed ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < beta_minus_one_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_minus_one" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_pi0";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "log1m_pi0";
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__) return;
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "pi0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha";
        param_names__.push_back(param_name_stream__.str());
        size_t beta_minus_one_k_0_max__ = (beta_fixed ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < beta_minus_one_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_minus_one" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_pi0";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "log1m_pi0";
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__) return;
    }

}; // model

}  // namespace

typedef model_pi0_namespace::model_pi0 stan_model;


#endif
